call plug#begin('~/.vim/plugged')

Plug 'valloric/youcompleteme'
Plug 'vim-scripts/wombat256.vim'
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable'}
Plug 'easymotion/vim-easymotion'
Plug 'ervandew/supertab'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'wincent/command-t'
Plug 'scrooloose/nerdtree'

call plug#end() 

set t_Co=256 " 256 color terminal

syntax on
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set autoindent
set number
set relativenumber
colorscheme wombat256mod
filetype indent plugin on

nnoremap ; :
imap jj <Esc>

let mapleader=" " 

set clipboard=unnamed " Os x clipboard when yanking

noremap Q <NOP> " Disable Ex mode

set ignorecase " case insensitive searching

" Move between splits with ctrl+hjkl (i.e no w)
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set backspace=indent,eol,start

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'
let g:ycm_confirm_extra_conf = 0 " Load settings files for youcompleteme without prompting

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

" Open Nerdtree with ctrl-n
map <C-n> :NERDTreeToggle<CR>
" Close vim if only nerdtree is open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
